#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@3.39.75.170:1521:XE
    username: hr
    password: hr
    #15.164.250.198

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: validate

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  #Summernote
#  summernote:
#    image:
#      upload-dir: /Users/hyun/uploads

#  app:
#    file:
#      upload-dir: /Users/hyun/uploads

  # 이미지 용량
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

      location: /C:/upload
#      location: /Users/hyun/uploads
      enabled: true

  session:
    store-type: redis

  #mail
  spring:
    mail:
    host: smtp.gmail.com
    port: 587
    username: 'simbongsa300@gmail.com'
    password: 'xtkwswcvlrrpvien'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          #naver
          naver:
            client-name: Naver
            client-id: CGhZTJz0uzH9cF8sHe71
            client-secret: 4ouXP37HyC
            redirect-uri: http://www.simbongsa.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email

          #kakao
          kakao:
            client-id: 7d1b8d2a934aea81ad94f34bb0bee10c
            redirect-uri: http://www.simbongsa.site/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: IEMgUxhifcob8cQfModdoRybzbdHD9gj
            authorization-grant-type: authorization_code
            scope: account_email
            client_name: kakao

        provider:
          #naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          #kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account


